
[project]
name = "comfyui_stereoscopic"
version = "2.0.0"
description = "Nodes to create stereoscopic images and movies."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.12"
dependencies = [ "torch", "opencv-python>=4.7.0.72", "numpy", "pillow", "googletrans" ]

[project.urls]
Repository = "https://github.com/FortunaCournot/comfyui_stereoscopic"

[tool.comfy]
PublisherId = "fortunacournot"
DisplayName = "Stereoscopic"
Icon = "https://raw.githubusercontent.com/FortunaCournot/comfyui_stereoscopic/refs/heads/main/docs/icon/VR2.png"

