---
# delete this file (in user\default\comfyui_stereoscopic) to reset it to defaults.
# After editing you have restart service daemon to apply changes.

pipeline:
  - from: caption
    keepinput: true
    forward:
      - rule:
          to: tasks/fps-limit-30
          conditions:
            - tvai=false
            - vram>8
      - rule:
          to: tasks/fps-limit-15
          conditions:
            - tvai=false
      - rule:
          to: scaling
  - from: tasks/fps-limit-15
    forward:
      - rule:
          to: scaling
  - from: tasks/fps-limit-30
    forward:
      - rule:
          to: scaling
  - from: scaling
    forward:
      - rule:
          to: tasks/hlimit-2160
          conditions:
            - tvai=false
            - calculated_aspect<1000
            - sbs=false
            - width>2160
      - rule:
          to: tasks/vlimit-2160p
          conditions:
            - tvai=false
            - sbs=false
            - height>2160
      - rule:
          to: tasks/vlimit-1080p
          conditions:
            - tvai=false
            - sbs=false
            - duration>90
      - rule:
          to: fullsbs
          conditions:
            - sbs=false
  - from: tasks/hlimit-2160
    forward:
      - rule:
          to: fullsbs
          conditions:
            - sbs=false
      - rule:
          to: watermark/encrypt
          conditions:
            - image=true
  - from: tasks/vlimit-2160p
    forward:
      - rule:
          to: fullsbs
          conditions:
            - sbs=false
      - rule:
          to: watermark/encrypt
          conditions:
            - image=true
  - from: tasks/vlimit-1080p
    forward:
      - rule:
          to: fullsbs
          conditions:
            - sbs=false
      - rule:
          to: watermark/encrypt
          conditions:
            - image=true
  - from: fullsbs
    keepinput: true
    forward:
      - rule:
          to: interpolate
          conditions:
            - duration<60
            - tvai=true
            - r_frame_rate<24
      - rule:
          to: tasks/limit-1920
          conditions:
            - duration<60
            - tvai=true
            - r_frame_rate<24
      - rule:
          to: tasks/limit-1600
          conditions:
            - duration<60
            - tvai=false
            - r_frame_rate<24
      - rule:
          to: singleloop
          conditions:
            - codec_type!=audio
            - duration<20
      - rule:
          to: dubbing/sfx
          conditions:
            - codec_type!=audio
      - rule:
          to: watermark/encrypt
  - from: tasks/limit-1600
    keepinput: true
    forward:
      - rule:
          to: interpolate
  - from: tasks/limit-1920
    keepinput: true
    forward:
      - rule:
          to: interpolate
  - from: interpolate
    keepinput: true
    forward:
      - rule:
          to: interpolate
          conditions:
            - r_frame_rate<24
      - rule:
          to: singleloop
          conditions:
            - codec_type!=audio
            - duration<20
      - rule:
          to: dubbing/sfx
          conditions:
            - codec_type!=audio
  - from: singleloop
    keepinput: true
    forward:
      - rule:
          to: dubbing/sfx
          conditions:
            - codec_type!=audio
  - from: tasks/forwarder
    forward:
      - rule:
          to: check/rate
  - from: check/rate
    forward:
      - rule:
          to: check/released
  - from: check/released
    forward:
      - rule:
          to: FLIMAGE_TARGET
          conditions:
            - image=true
      - rule:
          to: caption
          conditions:
            - video=true
  - from: slides
    keepinput: true
  - from: slideshow
    forward:
      - rule:
          to: dubbing/sfx
  - from: dubbing/sfx
    keepinput: true
    forward:
      - rule:
          to: tasks/pad-16-9-sbs
          conditions:
            - sbs=true
  - from: tasks/split-1m
    keepinput: true
  - from: tasks/createsilence
    keepinput: true
  - from: tasks/reencode
    keepinput: true
  - from: tasks/convertimage
    keepinput: true
  - from: tasks/convertvideo
    keepinput: true
