import os
import yaml


path = os.path.dirname(os.path.abspath(__file__))

# generate forward files
config_folder = os.path.join(path, "../../../../user/default/comfyui_stereoscopic")
yaml_def = os.path.join(config_folder, "autoforward.yaml")
with open(yaml_def) as stream:
    try:
        doc=yaml.safe_load(stream)
        forwards=doc["forwards"]
        errors=0
        for forward in forwards:
            sourceStage=forward["from"]
            rules=forward["rules"]
            if len(rules)>0:
                source_output_folder = os.path.join(path, "../../../../output/vr/"+sourceStage)
                if os.path.exists(source_output_folder):
                    forward_tmp = os.path.join(source_output_folder, "forward.tmp")
                    with open(forward_tmp, "w") as f:
                        f.write("# Autogenerated - will be reseted on next start of daemon. Edit autoforward.yaml instead.\n")
                        f.write("# Rules are executed in order until first condition (including file type) matches.\n")
                        for rule in rules:
                            targetStage=rule["rule"]["to"]
                            target_input_folder = os.path.join(path, "../../../../input/vr/"+targetStage)
                            if os.path.exists(target_input_folder):
                                try:
                                    conditions=rule["rule"]["conditions"]
                                    if len(conditions)>0:
                                        f.write("[")
                                        for c in range(len(conditions)):
                                            condition=conditions[c]
                                            if c>0:
                                                f.write(":")
                                            f.write(condition)
                                        f.write("]")
                                except KeyError as e:
                                    conditions=None
                                f.write(targetStage+"\n")
                            else:
                                print("Error: Invalid forward target stage '"+targetStage+"' defined for source stage '"+sourceStage+"'")
                                f.write("# Error: "+targetStage+" does not exist. Edit "+os.path.abspath(yaml_def)+"\n")
                                errors+=1
                    forward_final = os.path.join(source_output_folder, "forward.txt")
                    os.rename(forward_tmp,forward_final)
                else:
                    print("Error: Invalid forward source stage '"+sourceStage+"'")
                    errors+=1
        if errors>0:
            print(str(errors)+" error found! Fix them in "+os.path.abspath(yaml_def))
        
    except yaml.YAMLError as exc:
        print(exc)
        
